name = "notification-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# Environment variables - you'll need to set these in Cloudflare Dashboard
# or using wrangler secret put ONESIGNAL_REST_API_KEY
# [env.production.vars]
# ONESIGNAL_REST_API_KEY = "your-onesignal-rest-api-key-here"

# [env.staging.vars]
# ONESIGNAL_REST_API_KEY = "your-onesignal-rest-api-key-here"

# Optional: Add custom domains
# routes = [
#   { pattern = "notifications.yourdomain.com", zone_name = "yourdomain.com" }
# ]

# Optional: Add KV namespaces if you need to store data
# [[kv_namespaces]]
# binding = "NOTIFICATIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"